//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public int ID { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public Nullable<int> PackageDetailsId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblDestination tblDestination { get; set; }
        public virtual tblSource tblSource { get; set; }
    }
}
