//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLatLong
    {
        public int Id { get; set; }
        public string CityName { get; set; }
        public string LatAddress { get; set; }
        public string LongAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
