//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotation
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SourceAddress1 { get; set; }
        public string SourceAddress2 { get; set; }
        public string SourcePincode { get; set; }
        public string SourceCity { get; set; }
        public string SourceState { get; set; }
        public string SourceCountry { get; set; }
        public string DestinationAddress1 { get; set; }
        public string DestinationAddress2 { get; set; }
        public string DestinationCity { get; set; }
        public string DestinationState { get; set; }
        public string DestinationCountry { get; set; }
        public Nullable<int> PackageDeatilsId { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DestinationPincode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblPackageDetail tblPackageDetail { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual UserRegistration UserRegistration1 { get; set; }
        public virtual UserRegistration UserRegistration2 { get; set; }
    }
}
