//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int Id { get; set; }
        public int ShipmentId { get; set; }
        public int CargoStatusTypeId { get; set; }
        public string CurrentLocation { get; set; }
        public bool IsDelivered { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual CargoStatusType CargoStatusType { get; set; }
    }
}
