//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int Id { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> CargoStatusTypeId { get; set; }
        public string CurrentLocation { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual CargoStatusType CargoStatusType { get; set; }
        public virtual tblBooking tblBooking { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual UserRegistration UserRegistration1 { get; set; }
    }
}
